version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.27.4
  sonarcloud: extendaretail/sonarcloud@dev:alpha

jobs:
  test_npm:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace/test/npm
    steps:
      - checkout:
          path: ~/workspace
      - sonarcloud/scan_with_npm
      - sonarcloud/check_quality_gate

  test_maven:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/workspace/test/java
    steps:
      - checkout:
          path: ~/workspace
      - sonarcloud/scan_with_maven
      - sonarcloud/check_quality_gate

  test_gradle:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/workspace/test/java
    steps:
      - checkout:
          path: ~/workspace
      - sonarcloud/scan_with_gradle
      - sonarcloud/check_quality_gate

workflows:
  sonarcloud-orb:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: extendaretail/sonarcloud
          context: orb-publishing
          requires:
            - orb-tools/pack
      - test_npm:
          context: sonarcloud
          requires:
            - orb-tools/publish-dev
      - test_maven:
          context: sonarcloud
          requires:
            - orb-tools/publish-dev
      - test_gradle:
          context: sonarcloud
          requires:
            - orb-tools/publish-dev
